// lib/dummyData.ts
// Pre-loaded session simulating an Excel upload for Sarah L. Mitchell, Unit 204B.
// Used for UI mockup until real AppFolio Excel column names are confirmed.

import { SessionState } from '@/types';

export const DUMMY_SESSION: SessionState = {
  propertyName: 'Westlake Commons',
  uploadDate: '2026-06-26',
  returns: [
    {
      id: 'unit-204b-mitchell',
      processingStatus: 'in_progress',
      complianceChecked: false,
      pdfGenerated: false,
      tenantData: {
        tenantName: 'Sarah L. Mitchell',
        coTenant: '',
        unit: '204B',
        monthlyRent: 2800,
        moveInDate: '2023-03-01',
        moveOutDate: '2026-06-24',
        paidThroughDate: '2026-06-24',
        noticeDate: '2026-05-24',
        leaseEndDate: '2026-07-27',
        leaseBreak: true,
        newTenantMoveInDate: null,
        forwardingAddress: {
          street: '412 Elmwood Dr',
          city: 'Kirkland',
          state: 'WA',
          zip: '98033',
        },
        inspectionStatus: 'signed',
      },
      depositData: {
        securityDeposit: 1850,
        petDeposit: 300,
        keyDeposit: 0,
        garageOpenerDeposit: 0,
        nrcCleaningFee: 250,
        nrcPetFee: 0,
      },
      utilityData: {
        utilityType: 'RUBS',
        flatFeeRate: 0,
        flatFeeBillingMethod: 'included_in_rent',
        rubsBuildingTotal: 1240,
        rubsUnitRatio: 0.083,
      },
      ledgerData: {
        outstandingBalances: 0,
        lateFees: 0,
        credits: 0,
        partialPayments: 0,
        priorCharges: 0,
      },
      manualCharges: {
        generalCleaning: 350,
        blindDrapeCleaning: 0,
        windowCoveringReplacement: 0,
        carpetShampooing: 0,
        flooringRestoration: 0,
        painting: 0,
        other1Label: 'Key replacement',
        other1: 50,
        other2Label: '',
        other2: 0,
        legalCourtCosts: 0,
      },
      calculatedCharges: {
        rentDue: 2310,
        rentDueDateRange: '06/24/2026 – 07/27/2026',
        utilityCharge: 102.92,
      },
      rubsManualInput: {
        buildingTotal: 1240,
        unitRatio: 0.083,
      },
    },
    {
      id: 'unit-110a-okafor',
      processingStatus: 'not_started',
      complianceChecked: false,
      pdfGenerated: false,
      tenantData: {
        tenantName: 'James R. Okafor',
        coTenant: 'Dana K. Ng',
        unit: '110A',
        monthlyRent: 2200,
        moveInDate: '2024-01-15',
        moveOutDate: '2026-06-30',
        paidThroughDate: '2026-06-30',
        noticeDate: '2026-05-30',
        leaseEndDate: '2026-06-30',
        leaseBreak: false,
        newTenantMoveInDate: null,
        forwardingAddress: { street: '88 Pine Ave', city: 'Bellevue', state: 'WA', zip: '98004' },
        inspectionStatus: 'signed',
      },
      depositData: {
        securityDeposit: 2200,
        petDeposit: 0,
        keyDeposit: 0,
        garageOpenerDeposit: 0,
        nrcCleaningFee: 200,
        nrcPetFee: 0,
      },
      utilityData: {
        utilityType: 'flat_fee',
        flatFeeRate: 85,
        flatFeeBillingMethod: 'included_in_rent',
        rubsBuildingTotal: 0,
        rubsUnitRatio: 0,
      },
      ledgerData: { outstandingBalances: 0, lateFees: 0, credits: 0, partialPayments: 0, priorCharges: 0 },
      manualCharges: {
        generalCleaning: 0, blindDrapeCleaning: 0, windowCoveringReplacement: 0,
        carpetShampooing: 0, flooringRestoration: 0, painting: 0,
        other1Label: '', other1: 0, other2Label: '', other2: 0, legalCourtCosts: 0,
      },
      calculatedCharges: { rentDue: 0, rentDueDateRange: '', utilityCharge: 0 },
      rubsManualInput: null,
    },
    {
      id: 'unit-312d-nair',
      processingStatus: 'not_started',
      complianceChecked: false,
      pdfGenerated: false,
      tenantData: {
        tenantName: 'Priya S. Nair',
        coTenant: '',
        unit: '312D',
        monthlyRent: 1950,
        moveInDate: '2023-08-01',
        moveOutDate: '2026-07-01',
        paidThroughDate: '2026-07-01',
        noticeDate: '2026-06-01',
        leaseEndDate: '2026-07-01',
        leaseBreak: false,
        newTenantMoveInDate: null,
        forwardingAddress: { street: '55 Oak St', city: 'Redmond', state: 'WA', zip: '98052' },
        inspectionStatus: 'missing',
      },
      depositData: {
        securityDeposit: 1950,
        petDeposit: 0,
        keyDeposit: 0,
        garageOpenerDeposit: 0,
        nrcCleaningFee: 175,
        nrcPetFee: 0,
      },
      utilityData: {
        utilityType: 'RUBS',
        flatFeeRate: 0,
        flatFeeBillingMethod: 'included_in_rent',
        rubsBuildingTotal: 0,
        rubsUnitRatio: 0.072,
      },
      ledgerData: { outstandingBalances: 0, lateFees: 0, credits: 0, partialPayments: 0, priorCharges: 0 },
      manualCharges: {
        generalCleaning: 0, blindDrapeCleaning: 0, windowCoveringReplacement: 0,
        carpetShampooing: 0, flooringRestoration: 0, painting: 0,
        other1Label: '', other1: 0, other2Label: '', other2: 0, legalCourtCosts: 0,
      },
      calculatedCharges: { rentDue: 0, rentDueDateRange: '', utilityCharge: 0 },
      rubsManualInput: null,
    },
  ],
};
